### ISSUE TITLE
Annotation issue in the human gtf file?

### ISSUE THREAD

**Issue by MarijnBerg** [PoolLab/generecovery#3]
We had a look to see how it would affect and our data and while it’s mostly a great improvement we did have one weird artifact.

IGHD(B cell exclusive) is now detected in every cell at high level in our dataset of airway epithelium.
I traced this back to the .gtf file of the reference.
One of the exons of IGHD in there is listed as spanning from base chr14:306170 to chr14:105845677

**Comment by PoolLab** [comment]
Hi Marijn, Thank you for bringing this to my attention! It looks like the weird IGHD coordinate got pulled from Refseq annotation as an alternative extended 3' end and automatically altered. I will fix this in the next couple of days and upload the corrected version. Will give update here once it's up.

**Comment by PoolLab** [comment]
The IGHD issue is now fixed - I've uploaded the human optimized reference transcriptome v1.1 at https://www.thepoollab.org/resources. I found a similar issue with another gene on chromosome 15 (CPEB1) which is also now fixed in v1.1.
